name: Build Downstream Dependencies

on:
  push:

env: 
  CARGO_TERM_COLOR: always
jobs:
  cedar-examples:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current-repo
        uses: actions/checkout@v3

      - name: Checkout cedar-examples
        uses: actions/checkout@v3
        with:
          repository: cedar-policy/cedar-examples
          ref: main
          path: ./cedar-examples

      - name: Run downstream CI
        uses: ./cedar-examples/.github/workflows/ci.yml
        
